from puar.hetare import init_db,db_session
from puar.kamaseinu import YamchaMaster

init_db()

data1 = YamchaMaster('アメリカンカール','/static/gazou/illust/アメリカンカール.jpg')
db_session.add(data1)
data2 = YamchaMaster('アメリカンコッカ―スパニエル','/static/gazou/illust/アメリカンコッカ―スパニエル.jpg')
db_session.add(data2)
data3 = YamchaMaster('アメリカンショートヘア','/static/gazou/illust/アメリカンショートヘア.jpg')
db_session.add(data3)
data4 = YamchaMaster('イタリアングレーハウンド','/static/gazou/illust/イタリアングレーハウンド.jpg')
db_session.add(data4)
data5 = YamchaMaster('ウェルシュコーギーペンブローク','/static/gazou/illust/ウェルシュコーギーペンブローク.jpg')
db_session.add(data5)
data6 = YamchaMaster('エキゾチック','/static/gazou/illust/エキゾチック.jpg')
db_session.add(data6)
data7 = YamchaMaster('カニーンヘンダックスフンド','/static/gazou/illust/カニーンヘンダックスフンド.jpg')
db_session.add(data7)
data8 = YamchaMaster('キジトラ','/static/gazou/illust/キジトラ.jpg')
db_session.add(data8)
data9 = YamchaMaster('キャバリアキングチャールズスパニエル','/static/gazou/illust/キャバリアキングチャールズスパニエル.jpg')
db_session.add(data9)
data10 = YamchaMaster('ゴールデンレトリバー','/static/gazou/illust/ゴールデンレトリバー.jpg')
db_session.add(data10)
data11 = YamchaMaster('サイベリアン','/static/gazou/illust/サイベリアン.jpg')
db_session.add(data11)
data12 = YamchaMaster('サバトラ','/static/gazou/illust/サバトラ.jpg')
db_session.add(data12)
data13 = YamchaMaster('サビ猫','/static/gazou/illust/サビ猫.jpg')
db_session.add(data13)
data14 = YamchaMaster('シーズー','/static/gazou/illust/シーズー.jpg')
db_session.add(data14)
data15 = YamchaMaster('シェットランドシープドッグ','/static/gazou/illust/シェットランドシープドッグ.jpg')
db_session.add(data15)
data16 = YamchaMaster('シベリアンハスキー','/static/gazou/illust/シベリアンハスキー.jpg')
db_session.add(data16)
data17 = YamchaMaster('ジャックラッセルテリア','/static/gazou/illust/ジャックラッセルテリア.jpg')
db_session.add(data17)
data18 = YamchaMaster('スコティッシュフォールド','/static/gazou/illust/スコティッシュフォールド.jpg')
db_session.add(data18)
data19 = YamchaMaster('ソマリ','/static/gazou/illust/ソマリ.jpg')
db_session.add(data19)
data20 = YamchaMaster('チワワ','/static/gazou/illust/チワワ.jpg')
db_session.add(data20)
data21 = YamchaMaster('トイプードル','/static/gazou/illust/トイプードル.jpg')
db_session.add(data21)
data22 = YamchaMaster('ノルウェージャンフォレストキャット','/static/gazou/illust/ノルウェージャンフォレストキャット.jpg')
db_session.add(data22)
data23 = YamchaMaster('パグ','/static/gazou/illust/パグ.jpg')
db_session.add(data23)
data24 = YamchaMaster('パピヨン','/static/gazou/illust/パピヨン.jpg')
db_session.add(data24)
data25 = YamchaMaster('ビーグル','/static/gazou/illust/ビーグル.jpg')
db_session.add(data25)
data26 = YamchaMaster('ビジョンフリーゼ','/static/gazou/illust/ビジョンフリーゼ.jpg')
db_session.add(data26)
data27 = YamchaMaster('ブリティッシュショートヘア','/static/gazou/illust/ブリティッシュショートヘア.jpg')
db_session.add(data27)
data28 = YamchaMaster('フレンチブルドッグ','/static/gazou/illust/フレンチブルドッグ.jpg')
db_session.add(data28)
data29 = YamchaMaster('ペキニーズ','/static/gazou/illust/ペキニーズ.jpg')
db_session.add(data29)
data30 = YamchaMaster('ペルシャ','/static/gazou/illust/ペルシャ.jpg')
db_session.add(data30)
data31 = YamchaMaster('ベンガル','/static/gazou/illust/ベンガル.jpg')
db_session.add(data31)
data32 = YamchaMaster('ボーダーコリー','/static/gazou/illust/ボーダーコリー.jpg')
db_session.add(data32)
data33 = YamchaMaster('ボストンテリア','/static/gazou/illust/ボストンテリア.jpg')
db_session.add(data33)
data34 = YamchaMaster('ポメラニアン','/static/gazou/illust/ポメラニアン.jpg')
db_session.add(data34)
data35 = YamchaMaster('マルチーズ','/static/gazou/illust/マルチーズ.jpg')
db_session.add(data35)
data36 = YamchaMaster('マンチカン','/static/gazou/illust/マンチカン.jpg')
db_session.add(data36)
data37 = YamchaMaster('ミニチュアシュナウザー','/static/gazou/illust/ミニチュアシュナウザー.jpg')
db_session.add(data37)
data38 = YamchaMaster('ミニチュアダックスフンド','/static/gazou/illust/ミニチュアダックスフンド.jpg')
db_session.add(data38)
data39 = YamchaMaster('ミニチュアピンシャー','/static/gazou/illust/ミニチュアピンシャー.jpg')
db_session.add(data39)
data40 = YamchaMaster('ミヌエット','/static/gazou/illust/ミヌエット.jpg')
db_session.add(data40)
data41 = YamchaMaster('メインクーン','/static/gazou/illust/メインクーン.jpg')
db_session.add(data41)
data42 = YamchaMaster('ヨークシャーテリア','/static/gazou/illust/ヨークシャーテリア.jpg')
db_session.add(data42)
data43 = YamchaMaster('ラガマフィン','/static/gazou/illust/ラガマフィン.jpg')
db_session.add(data43)
data44 = YamchaMaster('ラグドール','/static/gazou/illust/ラグドール.jpg')
db_session.add(data44)
data45 = YamchaMaster('ラブラドールレトリーバー','/static/gazou/illust/ラブラドールレトリーバー.jpg')
db_session.add(data45)
data46 = YamchaMaster('ロシアンブルー','/static/gazou/illust/ロシアンブルー.jpg')
db_session.add(data46)
data47 = YamchaMaster('黒猫','/static/gazou/illust/黒猫.jpg')
db_session.add(data47)
data48 = YamchaMaster('三毛猫','/static/gazou/illust/三毛猫.jpg')
db_session.add(data48)
data49 = YamchaMaster('柴犬','/static/gazou/illust/柴犬.jpg')
db_session.add(data49)
data50 = YamchaMaster('秋田犬','/static/gazou/illust/秋田犬.jpg')
db_session.add(data50)
data51 = YamchaMaster('茶トラ','/static/gazou/illust/茶トラ.jpg')
db_session.add(data51)
data52 = YamchaMaster('白猫','/static/gazou/illust/白猫.jpg')
db_session.add(data52)


db_session.commit()
